### PR TITLE
add underscore to package.js

### PR DESCRIPTION
**Pull request by dan335**
I was getting this error.

```
TypeError: Object [object Object] has no method 'has'
at Object.configure (packages/okgrow_image-upload/lib/image_upload.js:141:1)
```

Fixed by adding underscore.

### CODE REVIEW

**Comment by pauldowman** [comment]
Thanks! We'll check it out asap.

**Comment by arrygoo** [comment]
@dan335 The error suggests that underscore does exist (as it should in Meteor's core) but it doesn't find 'has'. Can you share how you reproduce the bug?

**Comment by dan335** [comment]
Creating a package and adding this as a dependacy of the package makes it happen I think.

**Comment by arrygoo** [comment]
@dan335 Thanks. Merged! :+1:

**Pull request merged**
